### ISSUE TITLE
Tests fail locally

### ISSUE THREAD

**Issue by restor1** [afcastano/AutoValuePlugin#23]
Hi,

I tried to clone the master branch and build it locally according to the instructions but
tests fail due to com.intellij.util.IncorrectOperationException.

When 'targetClass.add(builderClass)' in AutoValueHandler::addBuilderElements is executed,
it results in a check of whether targetClass is writable through 'com.intellij.psi.impl.CheckUtil.checkWritable'. This check is delegated to the backing VirtualFile of that PSI which is apparently marked as not writable.
I tried to make sure that the testData files were accessible and writable, but the tests failed anyway.
I was able to get the tests working only by progrmatically marking the underlying Virtual Files as writable(which is a hack).
Any ideas?

specs:
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

stacktrace:
ERROR: Cannot modify a read-only file '/src/generatebuilder/basic/BasicTestFile.java'.
com.intellij.util.IncorrectOperationException: Cannot modify a read-only file '/src/generatebuilder/basic/BasicTestFile.java'.
	at com.intellij.psi.impl.CheckUtil.checkWritable(CheckUtil.java:47)
	at com.intellij.psi.impl.source.JavaStubPsiElement.add(JavaStubPsiElement.java:72)
	at com.afcastano.intellij.autovalue.generator.AutoValueHandler$1.addBuilderElements(AutoValueHandler.java:144)
	at com.afcastano.intellij.autovalue.generator.AutoValueHandler$1.run(AutoValueHandler.java:101)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:252)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:234)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:254)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:241)
	at com.afcastano.intellij.autovalue.generator.AutoValueHandler.processClass(AutoValueHandler.java:153)
	at com.afcastano.intellij.autovalue.generator.AutoValueHandler.invoke(AutoValueHandler.java:48)
	at com.afcastano.intellij.autovalue.intentions.BaseIntentionHandler.invoke(BaseIntentionHandler.java:30)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$3(ShowIntentionActionsHandler.java:196)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:200)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$null$1(ShowIntentionActionsHandler.java:186)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$2(ShowIntentionActionsHandler.java:185)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:184)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:168)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$invokeIntention$22(CodeInsightTestFixtureImpl.java:1814)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.ui.UIUtil.dispatchInvocationEvent(UIUtil.java:2108)
	at com.intellij.util.ui.UIUtil.dispatchAllInvocationEvents(UIUtil.java:2096)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.invokeIntention(CodeInsightTestFixtureImpl.java:1815)
	at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.launchAction(CodeInsightTestFixtureImpl.java:573)
	at com.afcastano.intellij.autovalue.AutoValuePluginTestUtils.runIntention(AutoValuePluginTestUtils.java:58)
	at com.afcastano.intellij.autovalue.AutoValuePluginTestUtils.runGenerateBuilderActions(AutoValuePluginTestUtils.java:31)
	at com.afcastano.intellij.autovalue.AutoValuePluginBuilderTest.testSimpleClass(AutoValuePluginBuilderTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$10(UsefulTestCase.java:311)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$11(UsefulTestCase.java:343)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:40)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:342)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:330)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:356)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:29)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:27)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$b0f40f3d.run(EdtTestUtil.kt)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by afcastano** [comment]
Thanks for letting me know.
I will see if I can reproduce over the weekend and come back to you!

**Comment by afcastano** [comment]
Hi,
I finally could reproduce it and it seems it is a problem in the latest SDK. I have run it with 2016.3 and the test are passing.
it is only a problem when running the tests though, the plugin works fine in all versions.

I added this note to the [doco](https://github.com/afcastano/AutoValuePlugin/blob/master/docs/PROJECT_SETUP.md):

>**NOTE:** Despite the plugin works on the latest version of IntelliJ, to run the tests you need to use the [SDK 2016.3](https://www.jetbrains.com/idea/download/previous.html) in the previous step. If you use 2017.1 the tests will throw an error. There is a question open in the [JetBrains support forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000389964-SDK-2017-1-cannot-modify-a-read-only-file-using-JavaCodeInsightTestFixture) if you want to track it.

**Comment by afcastano** [comment]
Hi @restor1 
There was an additional check added in SDK 2017.1, I have modified the code to make it compliant.
It also works with prior SDKs.
If you pull the code, the test should pass now.
Thanks and please let me know if this works so I can close the issue.
